FROM node:18 as build-deps

ARG ARG_VITE_URL_API
ENV VITE_URL_API=$ARG_VITE_URL_API

WORKDIR /usr/src/app

COPY src/package*.json ./

RUN curl -f https://get.pnpm.io/v6.16.js | node - add --global pnpm

ENV PATH="/pnpm:$PATH"
ENV PNPM_HOME="/pnpm"

RUN pnpm install

COPY src/. .

RUN pnpm build

RUN pnpm i -g serve

EXPOSE 5999

CMD [ "serve", "-s", "dist/", "-l", "5999"]