FROM node:18

ARG ARG_VITE_URL_API
ENV VITE_URL_API=$ARG_VITE_URL_API

WORKDIR /usr/src/app

COPY src/package*.json ./

RUN curl -f https://get.pnpm.io/v6.16.js | node - add --global pnpm

RUN pnpm install

RUN echo a

COPY src/. .

EXPOSE 5999

CMD [ "pnpm", "start" ]