FROM node:18

WORKDIR /usr/src/app

COPY src/package*.json ./

RUN curl -f https://get.pnpm.io/v6.16.js | node - add --global pnpm

RUN pnpm install

COPY src/. .

EXPOSE 5999

CMD [ "pnpm", "start" ]