FROM node:18

WORKDIR /usr/src/app

COPY src/package*.json ./

RUN curl -f https://get.pnpm.io/v6.16.js | node - add --global pnpm

RUN pnpm install

COPY src/. .

EXPOSE 6000 7000 7001 7002 7003 4001

CMD [ "pnpm", "start" ]